### ISSUE TITLE
Does the new version only support English

### ISSUE THREAD

**Issue by laozhuang727** [sidaw/shrdlurn#44]
Hi,

I am trying the latest code. Seems it only support the command list in the help me document. And the other command are totally not work.

May I know whether it is the feature of the new version?

**Comment by laozhuang727** [comment]
after read the video, I know the basic idea of your great tools. While still can not understand how to finish current game and move to next level

**Comment by sidaw** [comment]
not meant for public consumption yet!
I'm curious, how did you find the URL anyways? in package.json?

**Comment by sidaw** [comment]
To actually answer your question, yeah, we will start with English but we can go from there and teach it Chinese.
