### ISSUE TITLE
Bug in the live-demo

### ISSUE THREAD

**Issue by fgolemo** [sidaw/shrdlurn#74]
Hey guys,

great work on this project. I just wanted to ask: I tried the live-demo ( http://shrdlurn.sidaw.xyz/acl16/ ) some months ago and it was working fine, but I tried again today and the tasks aren't loading anymore. I.e. I just start out with an empty goal state, empty start state, and thus nothing to do. I check the error messages and it seems related to some JSON error.

Could you guys check please?

Cheers,
Florian

**Comment by ryansburgoyne** [comment]
+1 I would really like to try the demo, but I can't.

**Comment by sidaw** [comment]
Sorry, there was some AFS permission issue. I reset the server and it should work now.

**Comment by chankeypathak** [comment]
@sidaw Same issue again.
